[package]
name = "superconductor"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bevy_app = { version = "0.9", default-features = false }
bevy_ecs = { version = "0.9", default-features = false }
log = "0.4.17"
wasm-bindgen = "0.2.83"
renderer-core = { path = "renderer-core" }
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"
futures = "0.3.25"
wgpu = "=0.14.0"
anyhow = "1.0.68"
url = "2.3.1"
winit = "0.27.5"
arrayvec = "0.7.2"
surf = { version = "2.3.2", default-features = false }
bytemuck = "1.13.0"
futures-intrusive = "0.5.0"
image = "0.24.5"
glam = "0.22.0"
pollster = "0.2.5"

[dependencies.web-sys]
version = "=0.3.60"
features = [
    "HtmlButtonElement",
    "Document",
    "Navigator",
    "XrReferenceSpaceType",
    "XrSessionMode",
    "Navigator",
    "XrSystem",
    "XrSessionInit",
    "XrWebGlLayer",
    "XrWebGlLayerInit",
    "XrRenderStateInit",
    "XrRenderState",
    "XrReferenceSpace",
    "XrViewerPose",
    "XrView",
    "RequestInit",
    "Request",
    "Response",
]

[features]
wasm = ["renderer-core/wasm", "surf/wasm-client"]
webgl = ["wasm", "renderer-core/webgl"]
native = ["surf/curl-client"]

[workspace]
members = [
  "shared-structs",
  "gltf-helpers",
  "renderer-core",
  ".",
  "demo",
]

[patch.crates-io]
wgpu = { git = "https://github.com/expenses/wgpu", rev = "c6eebf3529d691828746c244e9e9e1124d078220" }
wgpu-hal = { git = "https://github.com/expenses/wgpu", rev = "c6eebf3529d691828746c244e9e9e1124d078220" }

[profile.dev]
debug = true
[profile.dev.package."*"]
opt-level = 3
[profile.dev.package.renderer-core]
opt-level = 3
[profile.dev.package.superconductor]
opt-level = 3
