[package]
name = "superconductor"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_app = { version = "0.8", default-features = false }
bevy_ecs = { version = "0.8", default-features = false }
log = "0.4.17"
wasm-bindgen = "0.2.80"
renderer-core = { path = "renderer-core" }
wasm-bindgen-futures = "0.4.31"
js-sys = "0.3.58"
futures = "0.3.21"
wgpu = "0.13.0"
anyhow = "1.0.58"
url = "2.2.2"
winit = "0.27.2"
arrayvec = "0.7.2"
surf = { version = "2.3.2", default-features = false }

[dependencies.web-sys]
version = "=0.3.58"
features = [
    "HtmlButtonElement",
    "Document",
    "Navigator",
    "XrReferenceSpaceType",
    "XrSessionMode",
    "Navigator",
    "XrSystem",
    "XrSessionInit",
    "XrWebGlLayer",
    "XrWebGlLayerInit",
    "XrRenderStateInit",
    "XrRenderState",
    "XrReferenceSpace",
    "XrViewerPose",
    "XrView",
    "RequestInit",
    "Request",
    "Response",
]

[features]
wasm = ["renderer-core/wasm", "surf/wasm-client"]
webgl = ["wasm", "renderer-core/webgl"]
native = ["surf/curl-client"]

[workspace]
members = [
  "shared-structs",
  "gltf-helpers",
  "renderer-core",
  ".",
  "demo",
]

[patch.crates-io]
glow = { git = "https://github.com/grovesNL/glow", rev = "11853d28ae64fbd7db5c856fe8b92a4a20fded94" }
wgpu = { git = "https://github.com/expenses/wgpu", rev = "d0e694833600605bd449f4cb54f01fca6b1e56d6" }
wgpu-hal = { git = "https://github.com/expenses/wgpu", rev = "d0e694833600605bd449f4cb54f01fca6b1e56d6" }

[profile.dev]
debug = true

[profile.dev.package.image]
opt-level = 3

[profile.dev.package.png]
opt-level = 3

[profile.dev.package.adler]
opt-level = 3

[profile.dev.package.miniz_oxide]
opt-level = 3
