[package]
name = "gltf-helpers"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bytemuck = { version = "1.9.1", features = ["derive"] }
glam = { version = "0.20.3", features = ["bytemuck"] }
log = "0.4.16"
ordered-float = "2.10.0"
goth-gltf = { git = "https://github.com/expenses/goth-gltf", rev = "584bfe250af13de6e9ea98e1d76d12e4ea92b2f2" }
