[package]
name = "shared-structs"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
glam = { version = "0.20.5", features = ["libm"], default-features = false }

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
crevice = { version = "0.10.0", features = ["glam"] }
bytemuck = { version = "1.9.1", features = ["derive"] }

[features]
webgl = []